package br.maua.cic303;

import java_cup.runtime.*;

parser code {:
    // Método chamado pelo CUP quando encontra um erro sintático
    public void syntax_error(Symbol cur_token) {
        throw new RuntimeException("Erro Sintático na linha " + cur_token.left + ", coluna " + cur_token.right);
    }
:}

/* ========================================================================= */
/* DECLARAÇÃO DOS TOKENS (TERMINAIS)                                         */
/* O CUP usará isso para gerar o sym.java que o seu Lexer precisa            */
/* ========================================================================= */

terminal IF, THEN, ELSE, WHILE;
terminal ASSIGN, LPAREN, RPAREN, LBRACE, RBRACE, SEMI;
terminal String ID, NUMBER;
terminal String ADD_OP, MUL_OP, REL_OP;

/* ========================================================================= */
/* DECLARAÇÃO DOS NÃO-TERMINAIS (VARIÁVEIS DA GRAMÁTICA)                     */
/* ========================================================================= */

non terminal program, stmt_list, stmt;
non terminal assign_stmt, if_stmt, while_stmt, block_stmt, null_stmt;
non terminal expr;

/* ========================================================================= */
/* PRECEDÊNCIA E ASSOCIATIVIDADE                                             */
/* ========================================================================= */

/* TODO 1: Declare a precedência para resolver a ambiguidade matemática. */
/* Dica: O operador mais embaixo tem a MAIOR precedência!                */
precedence left REL_OP;
precedence left ADD_OP;
precedence left MUL_OP;

/* ========================================================================= */
/* REGRAS DA GRAMÁTICA                                                       */
/* ========================================================================= */

start with program;

/* TODO 2: Como definir um programa que é uma lista de comandos? */
program ::= stmt_list ;

/* TODO 3: Como definir uma lista recursiva no BNF? */
stmt_list ::= stmt_list stmt
            | stmt
            ;

/* TODO 4: Declaração dos comandos (assign, if, while, block, null) */
stmt ::= assign_stmt
       | if_stmt
       | while_stmt
       | block_stmt
       | null_stmt
       ;

assign_stmt ::= ID ASSIGN expr SEMI ;

/* TODO 5: Implemente o IF, WHILE, BLOCO e NULL */
if_stmt ::= IF LPAREN expr RPAREN THEN block_stmt
          | IF LPAREN expr RPAREN THEN block_stmt ELSE block_stmt
          ;

while_stmt ::= WHILE LPAREN expr RPAREN block_stmt ;

block_stmt ::= LBRACE stmt_list RBRACE
             | LBRACE RBRACE
             ;

null_stmt ::= SEMI ;

/* TODO 6: Regras de expressões (aritmética, relacional, etc) */
expr ::= expr ADD_OP expr
       | expr MUL_OP expr
       | expr REL_OP expr
       | LPAREN expr RPAREN
       | NUMBER
       | ID
       ;
